source "http://rubygems.org"
gem "rake"
gem "cucumber", "=1.2.1"
gem "rspec", ">0"
gem "watir-webdriver", "=0.6.1"
gem "page-object", "=0.7.5.1"
gem "headless", ">0"
gem "data_magic", ">0"
gem "require_all", "=1.2.1"
gem "watir", :platforms => [:mswin, :mingw]